//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.09 at 09:40:20 AM WIB 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dickaspring.com/spring-boot-soap-demo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dickaspring.spring_boot_soap_demo;
